Fix fallback argument for Psych.load
This allows calling Psych.load with a fallback argument,
similar to Psych.load_file. Before, for Psych.load this
caused a "NoMethodError: undefined method `to_ruby'".